### ISSUE TITLE
Emmet disabled?

### ISSUE THREAD

**Issue by walterdavis** [textmate/dialog#22]
I noticed that Emmet was missing in the latest build 11.9, and when I try to re-install it, I get an alert saying "The Emmet plug-in should not be used with this version of TextMate because of stability problems." 

I don't see any issues around this, and no mention in the release notes. Can you give me any idea when or if it will be usable again?

Thanks,

Walter

**Comment by infininight** [comment]
You can see the commit that triggered this here with the reasoning:

https://github.com/textmate/textmate/commit/81d2586ffcfc9385d9bb362febda7c7ec8925557

We see a number of crashes related to the Emmet plugin and have decided to detect and block it from loading. If we can see a working/maintained fork of the plugin we can look at re-enabling the plugin by detecting that fork/version.

I've never really used emmet myself but the short investigation I've looked at suggested that perhaps it could be best done as a simple command rather than it's current plugin form. I didn't immediately see what it was doing that required a plugin rather than a command but I could be mistaken. Having it as a command would likely be more stable overall.

Closing this as it does not relate to the dialog plugin but feel free to reply if you have a question.

**Comment by sorbits** [comment]
You can remove Emmet from the blacklist by running this in a terminal, 
but as noted in the release notes, we get a lot of crashes from this 
plug-in, so only enable the plug-in if you are either OK with crashes, 
or your version is somehow without these issues:

     defaults write com.macromates.TextMate.preview disabledPlugIns 
-array
